//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClusteringAlgorithmsDataMining.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClusteringAlgorithmsDataMining.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBSCAN - clustering algorithm
        ///
        ///DBSCAN needs two elements:
        ///- epsilon which specifies how close points should be to each other to be considered a part of a cluster.
        ///- min points which specifies how many neighbors a point should have to be included into a cluster.
        ///
        ///Features:
        ///+Read data file.
        ///	-You can read cvs file type data. 
        ///	 When you open data file you need to select x and y data columns so it set all data to diagram.
        ///
        ///+Select data points points on the diagram.
        ///	-In Points section you can selec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoDBSCAN {
            get {
                return ResourceManager.GetString("InfoDBSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMEANS - clustering algorithm
        ///
        ///Features:
        ///+Read data file.
        ///	-When you open data you need select x and y data columns.
        ///
        ///+Select data points and cluster points on the diagram.
        ///	-In Data section you can select, remove, generate data and cluster points..
        /// </summary>
        internal static string InfoKmeans {
            get {
                return ResourceManager.GetString("InfoKmeans", resourceCulture);
            }
        }
    }
}
